# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path
import atexit
import json
import sys
from urllib.parse import urlparse

from config.policy import FEATURE_IDS, MANDATORY_FEATURES

# The feature policy is compiled into the PYZ archive as a Python module, not
# shipped as a data file: in onedir builds _internal/ is an ordinary folder, so
# a bundled .json is still one Notepad edit away from re-enabling everything.
# Editing a module inside the archive means unpacking and recompiling .pyc.
_root = Path(SPECPATH)
_generated_sources = (
    _root / 'config' / '_baked_policy.py',
    _root / 'config' / '_baked_deployment.py',
)


def _cleanup_generated_sources():
    for _generated_source in _generated_sources:
        try:
            _generated_source.unlink(missing_ok=True)
        except OSError as exc:
            print(f'[spec] WARNING: could not remove {_generated_source}: {exc}')


atexit.register(_cleanup_generated_sources)
_policy = json.loads((_root / 'feature-policy.json').read_text(encoding='utf-8-sig'))
_features = _policy.get('features') if isinstance(_policy, dict) else None
if not isinstance(_features, dict):
    raise ValueError('feature-policy.json must contain a features object')
_unknown = set(_features) - set(FEATURE_IDS)
_missing = set(FEATURE_IDS) - set(_features)
_non_boolean = sorted(k for k, v in _features.items() if not isinstance(v, bool))
_disabled_mandatory = sorted(k for k in MANDATORY_FEATURES if _features.get(k) is False)
if _unknown or _missing or _non_boolean or _disabled_mandatory:
    raise ValueError(
        'invalid feature policy: '
        f'unknown={sorted(_unknown)}, missing={sorted(_missing)}, '
        f'non_boolean={_non_boolean}, mandatory_disabled={_disabled_mandatory}')

_deployment = json.loads(
    (_root / 'company-defaults.json').read_text(encoding='utf-8-sig'))
_llm = _deployment.get('llm') if isinstance(_deployment, dict) else None
if not isinstance(_llm, dict):
    raise ValueError('company-defaults.json must contain an llm object')
_base_url = str(_llm.get('base_url') or '').strip().rstrip('/')
_parsed_url = urlparse(_base_url)
_primary_model = str(_llm.get('model') or '').strip()
_fallback_models = _llm.get('fallback_models', [])
_timeout = _llm.get('request_timeout', 120)
if (_parsed_url.scheme not in {'http', 'https'} or not _parsed_url.netloc
        or _parsed_url.hostname in {'localhost', '127.0.0.1', '::1'}):
    raise ValueError('company LLM URL must be a non-loopback http(s) URL')
if not _primary_model or not isinstance(_fallback_models, list):
    raise ValueError('company LLM model and fallback_models are required')
_models = []
for _model_value in [_primary_model, *_fallback_models]:
    _model_value = str(_model_value).strip()
    if not _model_value or len(_model_value) > 200:
        raise ValueError('company LLM model names must be non-empty and <= 200 characters')
    if _model_value not in _models:
        _models.append(_model_value)
if not isinstance(_timeout, int) or not 5 <= _timeout <= 600:
    raise ValueError('company LLM request_timeout must be an integer from 5 to 600')
if _llm.get('api_key'):
    raise ValueError('API keys must not be baked into company-defaults.json')
# Optional extra endpoints (each its own base_url/model). Validated the same way;
# no api_key is allowed here either, so no secret ever lands in the exe.
_endpoints = _llm.get('endpoints', [])
if not isinstance(_endpoints, list):
    raise ValueError('company LLM endpoints must be a list')
_baked_endpoints = []
_seen_models = set(_models)
for _entry in _endpoints:
    if not isinstance(_entry, dict):
        raise ValueError('each company LLM endpoint must be an object')
    if _entry.get('api_key'):
        raise ValueError('API keys must not be baked into company-defaults.json endpoints')
    _ep_name = str(_entry.get('name') or '').strip()
    _ep_url = str(_entry.get('base_url') or '').strip().rstrip('/')
    _ep_parsed = urlparse(_ep_url)
    _ep_model = str(_entry.get('model') or '').strip()
    if not _ep_name:
        raise ValueError('company LLM endpoint requires a name')
    if (_ep_parsed.scheme not in {'http', 'https'} or not _ep_parsed.netloc
            or _ep_parsed.hostname in {'localhost', '127.0.0.1', '::1'}):
        raise ValueError('company LLM endpoint URL must be a non-loopback http(s) URL')
    if not _ep_model or len(_ep_model) > 200:
        raise ValueError('company LLM endpoint model must be non-empty and <= 200 characters')
    if _ep_model in _seen_models:
        raise ValueError(f'company LLM model {_ep_model} appears in more than one endpoint')
    _seen_models.add(_ep_model)
    _baked_endpoints.append({'name': _ep_name, 'base_url': _ep_url, 'model': _ep_model})
_baked_llm = {
    'provider': 'company',
    'base_url': _base_url,
    'model': _models[0],
    'fallback_models': _models[1:],
    'request_timeout': _timeout,
    'endpoints': _baked_endpoints,
}
_generated_sources[0].write_text(
    '"""Generated by ClaudeCat.spec at build time - do not edit by hand."""\n'
    'FEATURES = ' + repr(_features) + '\n',
    encoding='utf-8')
_generated_sources[1].write_text(
    '"""Generated by ClaudeCat.spec at build time - do not edit by hand."""\n'
    'LLM = ' + repr(_baked_llm) + '\n',
    encoding='utf-8')
print(f'[spec] baked feature policy: '
      f'{sorted(k for k, v in _features.items() if not v) or "nothing disabled"}')
print(f'[spec] baked company LLM deployment: {len(_seen_models)} allowed model(s)'
      + (f', {len(_baked_endpoints)} extra endpoint(s)' if _baked_endpoints else ''))

_python_root = Path(sys.base_prefix)
_python_dlls = _python_root / 'DLLs'
_tk_binaries = [
    (str(_python_dlls / '_tkinter.pyd'), '.'),
    (str(_python_dlls / 'tcl86t.dll'), '.'),
    (str(_python_dlls / 'tk86t.dll'), '.'),
]

a = Analysis(
    ['cat.py'],
    pathex=[],
    binaries=_tk_binaries,
    # chat.html is a data file (not a Python import) - pywebview loads it
    # from disk by path, so PyInstaller's static import analysis can't see
    # it and it must be listed explicitly like skins/.
    datas=[('skins', 'skins'), ('frontend', 'frontend'), ('claudecat.ico', '.'),
           (str(_python_root / 'tcl'), 'tcl'),
           (str(_python_root / 'Lib' / 'tkinter'), 'tkinter')],
    hiddenimports=['tkinter', 'openpyxl', 'pptx', 'xlrd',
                   'pystray', 'pystray._win32', 'config._baked_policy',
                   'config._baked_deployment'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Pulled in by other packages' PyInstaller hooks (e.g. Pillow/requests
    # detecting these installed in the build env) even though this project
    # never imports them - excluding cuts ~50MB of dead weight from the exe.
    # win32com/win32api/win32con/pythoncom/pywintypes were excluded before
    # Part 2 - pywebview's Windows (Edge WebView2) backend actually needs
    # them, so only numpy/cryptography/win32ctypes stay excluded now.
    excludes=['cryptography', 'win32ctypes', 'pandas', 'numpy', 'pyarrow',
              'onnxruntime', 'grpc', 'oracledb', 'pypdfium2'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ClaudeCat',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='claudecat.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ClaudeCat',
)
